export enum Endpoints {
  COLLECTION = 'collections',
  CUSTOMERS = 'customers',
  BANNER = 'banners',
  PRODUCT = 'products',
  CLIENT = 'clients',
  CATEGORY = 'categories',
  VARIATION = 'variations',
  SKU = 'skus',
  BRAND = 'brands',
  SIMILAR = 'similars',
  COMMENT = 'comments',
  LEAD = 'leads',
  REVIEW = 'reviews',
  DISCOUNT = 'progressive-discounts',
}
